CREATE TABLE products (
    id                  UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id            UUID           NOT NULL,
    category_id         UUID,
    name                VARCHAR(255)   NOT NULL,
    slug                VARCHAR(255)   NOT NULL,
    description         TEXT,
    sku                 VARCHAR(100),
    price               DECIMAL(12, 2) NOT NULL,
    compare_at_price    DECIMAL(12, 2),
    cost_price          DECIMAL(12, 2),
    stock_quantity      INT            NOT NULL DEFAULT 0,
    low_stock_threshold INT            NOT NULL DEFAULT 5,
    track_inventory     BOOLEAN        NOT NULL DEFAULT TRUE,
    status              VARCHAR(20)    NOT NULL DEFAULT 'DRAFT',
    primary_image_url   TEXT,
    created_at          TIMESTAMP      NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP      NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_products_store_slug UNIQUE (store_id, slug),
    CONSTRAINT fk_products_store      FOREIGN KEY (store_id)    REFERENCES stores (id)     ON DELETE CASCADE,
    CONSTRAINT fk_products_category   FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
    CONSTRAINT chk_products_status    CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED')),
    CONSTRAINT chk_products_price     CHECK (price >= 0),
    CONSTRAINT chk_products_stock     CHECK (stock_quantity >= 0)
);
